services:
  backend:
    build:
      context: /backend/labseq
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
  
  frontend:
    build:
      context: /front/labseq
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend